# @package hydra.launcher
defaults:
  - submitit_slurm
timeout_min: 60
cpus_per_task: 8
tasks_per_node: 1
nodes: 1
name: ${hydra.job.name}

partition: cryoem
gres: gpu:a100:1
mem_per_cpu: 6gb
array_parallelism: 256