wandb:
  _target_: pytorch_lightning.loggers.wandb.WandbLogger
  name: ${name}
  save_dir: ${paths.exp_dir}
  offline: False
  id: null
  entity: chiulab
  project: CryoVIT
  group: ${datamodule.sample}
  log_model: False