project_dir: /home/vivian/Documents/Work/Data
data_dir: /home/vivian/Documents/Work/Data/cryovit-data
exp_dir: /home/vivian/Documents/Work/Results/CryoVIT

# tomo_name: ???
# feature_name: ???
# dino_name: ???
# csv_name: ???
# split_name: ???

#### DO NOT CHANGE ####

defaults:
  - base_env