# This workflows will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries
name: Publish Python Package to PyPI

on:
  push:
    tags:
      - 'v*'  # Trigger on version tags like v1.0.0

jobs:
  deploy:
    name: Publish Distribution to PyPI
    if: contains(github.ref, 'tags')
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - name: Install pypa/build
        run: |
          python -m pip install --upgrade pip
          pip install -U setuptools setuptools_scm wheel build
          git tag
          python -m build .
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
